name: turlgo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^12.0.0
  flutter_svg: ^2.0.17
  provider: ^6.1.4
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  shimmer: ^3.0.0
  pin_code_fields: ^8.0.1
  flutter_secure_storage: ^9.2.4
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.12
  youtube_player_flutter: ^9.1.1
  webview_flutter: ^4.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
